Add metric for failed and succeeded repair tasks per table
Ericsson/ecchronos pull request #296
Opened 2022-04-19 08:07 UTC by masokol

The new metric is a sliding window metric, counting average failed repair sessions the last 1 minute, 5 minutes and 15 minutes.
Closes #295

2022-04-20 09:25 UTC, tommystendahl approved these changes

2022-06-01 12:13 UTC, itskarlsson requested changes

2022-06-15 09:56 UTC, masokol commented on docs/METRICS.md
> +    The amount of repair sessions that have failed for the repair job. The metric is reset each time repair job runs.
As discussed, we would like to have failed repairs over time (rate like).
For this we need dropwizard metrics 4.X and most probably cassandra driver 4.X.

From my local testing, stepping driver major version will be a big task so this PR will have to wait until then.

2022-08-11 06:48 UTC, tommystendahl approved these changes

2022-08-11 08:50 UTC, itskarlsson commented on docs/METRICS.md
> +| 1660042648 | 0     | 0.000000  | 0.000000 | 0.000000 | 0.000000 | events/second |
This is valuable information. Perhaps we should also add a counter for succeeded RepairTasks.

2022-08-12 08:05 UTC, itskarlsson commented on docs/METRICS.md
> +in healthy clusters (assuming repairs are actually running).
"(assuming repairs are actually running)"

Should be 0 even if repairs are not running

Something like:
" should be close to `0` in healthy clusters. A positive rate might indicate a problem and warrant a look into the logs."

2022-08-12 08:05 UTC, itskarlsson commented on docs/METRICS.md
> +If repairs are not running the `m1_rate`, `m5_rate` and `m15_rate` will also show `0`.
will show '0'.

2022-08-12 08:21 UTC, itskarlsson approved these changes

2022-08-12 08:33 UTC, merged