Drop support for Java 8
Ericsson/ecchronos pull request #494
Opened 2023-06-02 07:15 UTC by masokol

The consequence of this is that we won't be testing with Cassandra < 4.
Closes #493

2023-06-02 09:24 UTC, tommystendahl approved these changes

2023-06-05 11:54 UTC, itskarlsson requested changes

2023-06-05 11:54 UTC, itskarlsson commented on .github/workflows/actions.yml
>             java: 11
This is not really necessary to specify anymore on each matrix entry. We can put the java version directly into the step.

2023-06-05 11:54 UTC, itskarlsson commented on README.md
> +* JDK11
CONTRIBUTING.md also has a reference to prerequisites that specify JDK8.
Prerequisites

    Maven
    JDK8
    Docker (for test setup)
    Python

2023-06-05 13:17 UTC, itskarlsson approved these changes

2023-06-07 05:27 UTC, merged