Enhancement of ARCHITECTURE.md Documentation - Issue #578
Ericsson/ecchronos pull request #579
Opened 2023-09-21 16:27 UTC by VictorCavichioli

In order to provide detailed information about software components, Enhancements to architecture documentation are desired to better understand the system's structure and enable informed design decisions.

2023-09-22 06:29 UTC, masokol requested changes

2023-09-22 06:29 UTC, masokol commented on docs/ARCHITECTURE.md
> +In the context of Apache Cassandra, a "lease" refers to a mechanism employed during the repair process within Cassandra.
I find this information a bit too generic, this document should be in the context of ecChronos not Cassandra. We already explain how ecChronos achieves coordination on the locks(leases) below. Maybe just adding a reference would be enough.

2023-09-22 06:29 UTC, masokol commented on docs/ARCHITECTURE.md
> +<figure>
This picture is incorrect, it should be
schedule manager -> refresh priorities -> pick job with highest priority -> should job run (run policy)
yes -> Create job tasks -> execute tasks -> schedule manager
no -> take next job -> should job run (run policy)

2023-09-22 06:29 UTC, masokol commented on docs/ARCHITECTURE.md
> +* (20, 30] repaired at X5f
X5f?

2023-09-22 08:06 UTC, jwaeab commented on docs/images/ecchronos-instances.png
Ecchronos -> ecChronos

Also, if the ecChronos instance and Cassandra node runs on the same entity in this picture, perhaps they should be grouped together. Looking at the picture now, it seems all instances/nodes run in seperate environments.

2023-09-22 08:06 UTC, jwaeab commented on docs/ARCHITECTURE.md
> +Upon the initiation of a repair in a Cassandra cluster, a "lease" is granted to one of the cluster nodes, which serves as the repair coordinator. This coordinating node is responsible for overseeing
Why the use of "lease" everywhere? Why not just use lease (without citation) if that's the correct word?

2023-09-22 08:06 UTC, jwaeab commented on docs/ARCHITECTURE.md
> +    <figcaption >Figure 2: Lease Typically Election.</figcaption>
Unnecessary space after each figcaption tag.

2023-09-22 08:06 UTC, jwaeab commented on docs/images/repair-job-flow.png
What's up with the black dot? Void? ;-)

What will make the dot do the transition from its state to Schedule Manager again? Why is it marked red?

2023-09-26 14:50 UTC, VictorCavichioli commented on docs/ARCHITECTURE.md
> +* (20, 30] repaired at X5f
It was a mistake, sorry.

2023-09-26 14:51 UTC, VictorCavichioli commented on docs/images/repair-job-flow.png
In states machines it means "end", but based on previously conversations we've decided to change a little bit this diagram and remove this.

2023-09-27 06:53 UTC, masokol requested changes

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +<div align="center">
This chart looks really strange, see if you can get it more spaced out. Right now it looks like each ecchronos is connected to 2 cassandra nodes.

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +    A[Create Lease] -->|Succeeded| c[Become Master]
There's no master concept in ecchronos, you either get the lock or not.

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +      RepairScheduler --> CreateRepairJob
This should be "CreateSchedules" or "CreateRepairJobs"

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +* (20, 30] repaired at X5f
it's still X5f

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +In the context of Apache Cassandra, a "lease" refers to a mechanism employed during the repair process within Cassandra.
This is not true, in context of Cassandra there's no "lease" during repair process. "Lease" is something you have to implement on the application level (like ecchronos, already described below)

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +Upon the initiation of a repair in a Cassandra cluster, it's granted to one of the cluster nodes, which serves as the repair coordinator. This coordinating node is responsible for overseeing the repa
This is not true either, there are no leases in Cassandra.

2023-09-27 06:53 UTC, masokol commented on docs/ARCHITECTURE.md
> +      ShouldJobRunCondition --> CreateJobTask: Yes
CreateJobTasks

2023-10-04 06:21 UTC, jwaeab approved these changes

2023-10-04 06:28 UTC, merged