Make priority granularity configurable #599
Ericsson/ecchronos pull request #610
Opened 2023-10-21 12:38 UTC by SajidRiaz138

2023-10-23 09:36 UTC, masokol commented on application/src/main/resources/ecc.yml
> +  ##  It determines how often the priority is recalculated.
"It determines how often the priority is recalculated." this is not true. It's used to calculate priority not "how often".

2023-10-23 09:36 UTC, masokol commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/scheduling/ScheduledJob.java
> +        long granularityInMs = TimeUnit.MILLISECONDS.convert(1, myGranularityUnit);
myGranularityUnit.toMillis(1);

2023-10-23 09:36 UTC, masokol commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/repair/TestTableRepairJob.java
> +    {
Add a testcase for overflow.

2023-10-23 09:36 UTC, masokol commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/scheduling/ScheduledJob.java
> +        public final TimeUnit granularityUnit;
priorityGranularity

2023-10-25 06:26 UTC, jwaeab requested changes

2023-10-25 06:26 UTC, jwaeab commented on application/src/main/resources/ecc.yml
> +  ##  Ensure to pause repair operations when changing the granularity to maintain consistency.
'when' should probably be something as 'prior to', just to be crystal clear of when to do it.

2023-10-25 06:26 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairConfiguration.java
> +@SuppressWarnings ("FinalClass")
Why a space in between?

2023-10-25 06:26 UTC, jwaeab commented on docs/UPGRADE.md
> +Ensure to pause repair operations when changing the granularity to maintain consistency.
Same comment as for 'ecc.yml'.

2023-10-25 06:26 UTC, jwaeab commented on docs/UPGRADE.md
> +HOURS  # or MINUTES, SECONDS. It’s important to note that while making these changes,
This line looks strange. Copy+paste problem?

2023-10-25 08:21 UTC, jwaeab approved these changes

2023-10-25 08:42 UTC, jwaeab approved these changes

2023-10-25 08:52 UTC, merged