Issue 397 Metric reporter to log debug messages if configured number …
Ericsson/ecchronos pull request #662
Opened 2024-05-14 11:16 UTC by manmagic3

Metric inspector to read metrices every 5 seconds. It will check if number of failed repairs in a time window (default 30 minutes) exceed to that configured value in yaml file. If identifies that there are these many repairs in defined time window, then debug messages are printed with some of the metrices,showing status of the system at that moment. Also the timewindow is reconfigured to start next time window.

2024-05-15 10:46 UTC, jwaeab requested changes

2024-05-15 10:46 UTC, jwaeab commented on application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/config/metrics/StatisticsConfig.java
> +    private int myTimeWindowSizeinMinsForReporting = 0;
Camel case; "...SizeInMins..."

2024-05-15 10:46 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +     @VisibleForTesting
Indentations

2024-05-15 10:46 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +    private LocalDateTime recordingStartTimestamp = LocalDateTime.now();
myRecordingStartTimestamp

2024-05-15 10:46 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +            if (myTotalRecordFailures - myRepairFailureCountSinceLastReport > myRepairFailureThreshold)
Will this eventually overflow?

2024-05-15 10:46 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +
Lots of extra line breaks here.

2024-05-15 10:46 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/StatusLogger.java
> + */
Clean up this comment a bit.

2024-05-15 10:46 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        assertEquals("Total repair success in node till now is:1", logMessage);
Space after ':' missing (with the fix commented above)

2024-05-15 10:46 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        assertEquals("Node last repaired at",logMessage.substring(0, 21));
space before logMessage.substring(...)

2024-05-15 10:46 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        TableReference tableReference = tableReference(TEST_KEYSPACE, TEST_TABLE1);
Would name this as tableReference1, to keep the consistency (as for the rest of this test method)

2024-05-15 10:46 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +
Remove the extra line breaks.

2024-05-15 10:46 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        TableReference tableReference = tableReference(TEST_KEYSPACE, TEST_TABLE1);
tableReference1

2024-05-24 12:18 UTC, manmagic3 commented
Hi Johan, I still need to address some comments from Macan and also need to write more test cases.

2024-05-30 08:27 UTC, manmagic3 commented
Johan added the test cases and made some changes as per some comments by Makan. You can proceed with review.

2024-06-03 06:05 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TestMetricInspector.java
> +        TableReference tableReference1 = tableReference(TEST_KEYSPACE, TEST_TABLE1);
You're not using "tableReference1" in this test? Why?

It is confusing when you name some variables without a number and some with and they're essentially referencing to the same table (TEST_TABLE1). Eg:
tableReference
tableReference1

Why not?
tableReference1
tableReference2

2024-06-03 06:07 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TestMetricInspector.java
> +        TableReference tableReference1 = tableReference(TEST_KEYSPACE, TEST_TABLE1);
Again, why tableReference1, when it is not being referenced in the test case?

2024-06-03 06:10 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TestMetricInspector.java
> +        expectedRepairTime = 12345L;
Why setting it to the same value?

2024-06-03 06:12 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        assertEquals("Node Repair Ratio is: 1.0", logMessage);
Why capitol R? "Node repair ratio"

2024-06-03 06:13 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/StatusLogger.java
> +            LOG.debug("Node Repair Ratio is: {}", nodeRepairedRatio.value());
Why capitol R's?

2024-06-03 06:14 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +    void inspectMeterRegistryForRepairFailures()
Fix code formatting for this method.

2024-06-03 06:15 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +     {
Formatting

2024-06-03 06:16 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TestStatusLogger.java
> +        Double expectedRepairTime = (double) (expectedRemainingRepairTime+expectedRemainingRepairTime2) / 1000;
Formatting "...RepairTime1 + expectedRemaining..."

2024-06-03 06:22 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TestMetricInspector.java
> +        myMetricInspector = new MetricInspector(myMeterRegistry,
Code formatting

2024-06-03 06:23 UTC, jwaeab commented on core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TestMetricInspector.java
> +    @Mock
Perhaps a blank line here

2024-06-03 06:23 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +    void resetRepairFailureCount()
Formatting

2024-06-03 06:25 UTC, jwaeab commented on application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/ECChronosInternals.java
> +                    configuration.getStatisticsConfig().getRepairFailuresTimeWindowInMinutes(),
Why do you need this specialized method here?

2024-06-03 06:25 UTC, jwaeab commented on application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/ECChronosInternals.java
> +                    configuration.getStatisticsConfig().getTriggerIntervalForMetricInspectionInMillSeconds());
Why do you need this specialized method here?

2024-06-09 07:38 UTC, manmagic3 commented
Documentation updatated, comments addressed.

2024-06-10 05:25 UTC, jwaeab requested changes

2024-06-10 05:25 UTC, jwaeab commented on application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/config/metrics/StatisticsConfig.java
> +    private static final int DEFAULT_REPAIR_FAILURE_COUNT = 5;
"failures", to keep it consistent; DEFAULT_REPAIR_FAILURES_COUNT

2024-06-10 05:25 UTC, jwaeab commented on application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/config/metrics/StatisticsConfig.java
> +    private static final int DEFAULT_FAILURE_TIME_WINDOW_IN_MINUTES = 30;
"failures", to keep it consistent; DEFAULT_FAILURES_TIME_WINDOW_IN_MINUTES

2024-06-10 05:25 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +       public MetricInspector(final MeterRegistry meterRegistry,
Formatting

2024-06-10 05:25 UTC, jwaeab commented on core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/MetricInspector.java
> +        io.micrometer.core.instrument.Timer nodeRepairSessions = myMeterRegistry
Formatting in the entire method should be cleaned up.

2024-06-10 05:25 UTC, jwaeab commented on docs/METRICS.md
> +Whenever metric is enabled, a logger is triggered which monitors metrics for
monitor

2024-06-10 05:25 UTC, jwaeab commented on docs/METRICS.md
> +overshoot the number(`repair_failures_count`) configured in ecc.yml within a time
... within the time ...

2024-06-14 09:05 UTC, manmagic3 commented
Hi Johan I have closed all review comments.

2024-06-17 04:32 UTC, jwaeab approved these changes

2024-06-17 04:35 UTC, jwaeab requested changes
You need to update CHANGES.md as well as have a look at the conflicts

2024-06-17 05:13 UTC, jwaeab submitted a review, later dismissed

2024-06-17 07:02 UTC, tommystendahl approved these changes

2024-06-17 07:02 UTC, merged